; [pytest]
; addopts =-v --html=reports/report.html --self-contained-html --capture=tee-sys
         



; [playwright]
; browser = chromium
; headed = false
; video = retain-on-failure
; ; screenshot = only-on-failure
; tracing = retain-on-failure

